version: '3.1'

services:
  db:
    image: bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=sustc
